### ISSUE TITLE
Preserve continuity of edition in automation frame

### ISSUE THREAD

**Issue by bl0b** [bl0b/renoise-xtouch-xctl.xrnx#10]
followup to #3 
There are two different things at work:
 - [x] When scrolling left and right, lanes where `recording` is set must remain visible and stack. If 8 lanes are set to record, no effective scrolling is possible.
- [x] When switching patterns, lanes set to record must remain in place and pattern_track automation created as necessary.

**Comment by nickcent** [comment]
What is this? I haven't come across any lanes yet... Have you managed to create separate lanes?? That would be sick!

**Comment by bl0b** [comment]
Implemented in 0f21b6cacab5750bd563581b29871516025f49a0

While set to `recording`, a lane stays on the same X-Touch channel. Scrolling only affects lanes where `recording` is not set. If switching patterns, new automations will be created as needed.
