### ISSUE TITLE
'Global View' buttons crashes the tool.

### ISSUE THREAD

**Issue by nickcent** [bl0b/renoise-xtouch-xctl.xrnx#11]
Pressing the Global View button brings about some extra tracks on the mixer and if pressed again, the tool crashes and pop up a dialog.

**Comment by bl0b** [comment]
I'm going to need details like a screenshot of the dialog as well as instructions to reproduce the bug. When a crash happens, open the scripting terminal (it has to be enabled first in the renoise config XML, it's in their wiki), reload the tool (or restart renoise if the crash was too bad), and repeat what you did to crash it again. The tool will dump a lot of messages in the terminal, if it is already open, which you can copy-paste on github or attach as a text file.

The `GLOBAL VIEW` button toggles the VU LEDs support. To do this it creates 8 send tracks, one for each X-Touch channel, and the tool will add `#Send` devices on the tracks as it needs. The fact that it crashes on the second press means that it's probably some device or track that it expected to be there doesn't exist.
I haven't encountered a condition where the VU support crashes recently. Do you have less than 8 tracks in this song? (That's part of the details I need to know to understand the bug)

**Comment by nickcent** [comment]
I can't seem to be able to reproduce this bug. Good one.

**Comment by bl0b** [comment]
OK I'm going to close the issue until either of us reproduces the bug.
