### ISSUE TITLE
PLUG-IN: Scribble Strip :Parameters are not what they claim to be!

### ISSUE THREAD

**Issue by nickcent** [bl0b/renoise-xtouch-xctl.xrnx#13]
Each parameters shows up on the little screen, but it actually is the parameter before the parameter shown. 
Control parameters are offset by one. As in, the screen says Thrshld but affects Ratio. (the perimeter next)

**Comment by bl0b** [comment]
Need details. Which device? Is it a systematic behaviour?

**Comment by bl0b** [comment]
ab2c943ff8fa6aee71cb03889254104a7d4b1690 should fix it. I rewrote a few things in the course of understanding this bug that should help with the continuity of edits in the automation page too.

**Comment by bl0b** [comment]
@nickcent please confirm whether it's fixed.

**Comment by nickcent** [comment]
It now works beautifully! I also found something odd! While being at the PLUG-IN page, and pressing SHIFT and turning the first encoder, changes the Width of the renoise track. Is this intentional? It's great, but you have to tell me about hidden gems like that! I'm thrilled of your coding abilities! :D
