### ISSUE TITLE
Can't get out of SEND Page.

### ISSUE THREAD

**Issue by nickcent** [bl0b/renoise-xtouch-xctl.xrnx#15]
I am stuck in Sends Page. There is no way to switch to Pan/Surround or any other 'Page'.

**Comment by bl0b** [comment]
Not even with the `ENCODER ASSIGN` buttons?

**Comment by nickcent** [comment]
nope...

**Comment by bl0b** [comment]
look for error messages in the terminal. Also, please update the tool to the latest commit (just delete the directory, and perform the git clone command I mentioned)

**Comment by nickcent** [comment]
Tool updated. Issue no longer there.
