### ISSUE TITLE
`GROUP` should be used to follow automation lanes when switching patterns

### ISSUE THREAD

**Issue by bl0b** [bl0b/renoise-xtouch-xctl.xrnx#9]
The bigger problem with automation grouping is less about splitting by tracks within a pattern than it is about continuity of edits across patterns. If `GROUP` is lit, the tool should keep the currently edited lanes (with recording flag set) in the same X-Touch channel when the pattern changes, creating them as needed.

**Comment by bl0b** [comment]
Linking to #10

**Comment by bl0b** [comment]
It's probably going to need a redesign of the frame values definition

**Comment by nickcent** [comment]
?

**Comment by bl0b** [comment]
@nickcent don't worry, it's just notes to self. What I call a frame is the part of the mappings that relates to the X-Touch tracks and that can be moved around with the left/right buttons.

**Comment by bl0b** [comment]
To Renoise, automation is defined inside patterns in the sequence, so switching patterns changes all the automation lanes. What I want is that when the recording light is set on a lane, it stays there on the X-Touch on any pattern you transport to.
To the tool, scrolling left and right was also resetting all the state, so a lane with recording set would not have recording set any more after a press on `CHANNEL / RIGHT` for instance. What I want is that when you scroll left or right, whatever lane that is currently recording stays in recording mode and also stays mapped on the X-Touch (so ultimately you could have 8 lanes recording at the same time, even if they are not right next to each other in Renoise, but then can't scroll any more until recording mode is unset on a lane).
I should actually close this issue because #10 is the broader picture.

**Comment by bl0b** [comment]
Now that the recording lanes are sticky, I think using `GROUP` to display automation in one track / all tracks is a good choice.
